language: ruby
rvm: 1.9.3
env:
  - DB=postgresql
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database putne_test' -U postgres
  - cp config/database.travis.yml config/database.yml
